language: php
php:
  - 7.0

addons:
  firefox: latest
  chrome: stable

before_script:
  - 'php -S 127.0.0.1:8080 &'
  - 'nvm install stable'
  - 'npm install nightwatch@1.1.0 selenium-server chromedriver geckodriver'

script:
  - 'node_modules/.bin/nightwatch -e firefox-headless'
